doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            tenant:
                user: appuser
                password: apppassword
                host: localhost
                wrapper_class: Parthenon\MultiTenancy\Dbal\TenantConnection
                driver: pdo_pgsql
            timescale:
                url: '%env(resolve:TIMESCALE_URL)%'

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        resolve_target_entities:
            Parthenon\User\Entity\UserInterface: App\Entity\User
            Parthenon\User\Entity\TeamInterface: App\Entity\Team
            Parthenon\Billing\Entity\CustomerInterface: App\Entity\Team
            Parthenon\Billing\Entity\BillingAdminInterface: App\Entity\User
            Parthenon\Billing\Entity\PaymentInterface: App\Entity\Payment
            Parthenon\Billing\Entity\ProductInterface: App\Entity\Product
            Parthenon\Billing\Entity\ReceiptInterface: App\Entity\Receipt
            Parthenon\Billing\Entity\ReceiptLineInterface: App\Entity\ReceiptLine
            Parthenon\Billing\Entity\PriceInterface: App\Entity\Price
            Parthenon\Billing\Entity\TierComponentInterface: App\Entity\TierComponent
            Parthenon\Billing\Entity\SubscriptionInterface: App\Entity\Subscription
            Parthenon\Billing\Entity\SubscriptionPlanInterface: App\Entity\SubscriptionPlan
            Parthenon\MultiTenancy\Entity\TenantInterface: App\Entity\Tenant
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            tenant:
                connection: tenant
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/MultiTenant/Entity'
                        prefix: 'App\MultiTenant\Entity'
                        alias: App
