parthenon:
  ab_testing:
    enabled: true
    parthenon:
      dbal_connection_service: 'Doctrine\DBAL\Connection'
      log_user_results: true
      predefined_decisions_enabled: true
      predefined_decisions_redis_service: 'Redis'
      disabled_user_agents:
        - 'Go\-http\-client'
        - 'python'
        - 'Google'
        - 'bingbot'
        - 'SemrushBot'
        - 'AhrefsSiteAudit'
        - 'AhrefsBot'
        - 'SeznamBot'
        - 'SaaSHub'
        - 'expanseinc'
        - 'masscan'
        - 'Kryptos Logic Telltale'
        - 'zgrab'
        - 'PocketImageCache'
        - 'Linux Gnu \(cow\)'
        - 'Slackbot'
        - 'Java'
        - 'Hello, World'
        - 'TweetmemeBot'
        - 'CensysInspect'
        - 'YandexBot'
        - 'ZmEu'
        - 'curl'
        - 'SEOkicks'
        - 'GRequests'
        - 'Barkrowler'
        - 'BLEXBot'
        - 'http(s)?\:\/\/'
        - 'Xenu'
        - 'Go http'
        - 'Twitterbot'
        - 'facebookexternalhit'
        - 'Facebot'
        - 'adbeat'
        - 'NetSystemsResearch'
        - 'Cloudflare-SSLDetector'
  multi_tenancy:
    enabled: true
    background_creation: false
    domain: ha-local.xyz
    migrations:
      directory: '%kernel.project_dir%/multi_tenancy_migrations'
    doctrine:
      global_dbal_connection: default
      dbal_connection: tenant
      orm_entity_manager: tenant
      default_database: '%env(resolve:TENANT_DEFAULT_DATABASE)%'
  common:
    elasticsearch:
      connection_type: 'normal'
      hosts: ['%env(resolve:ELASTICSEARCH_HOST)%']
      basic_username: elastic
      basic_password: changeme
    pdf:
      generator: 'wkhtmltopdf'
      wkhtmltopdf:
        bin: '/usr/bin/wkhtmltopdf'
  user:
    enabled: true
    user_class: App\Entity\User
    team_class: App\Entity\Team
    user_invites_enabled: true
    teams_enabled: true
    login_route: "parthenon_user_login"
    teams_invites_enabled: true
  notification:
    enabled: true
    email:
      from_name: 'Parthenon'
      from_address: 'support@parthenon.email'
      provider: sendgrid
      sendgrid:
        api_key: '%env(resolve:SENDGRID_API_KEY)%'

  athena:
    enabled: true
  payments:
    enabled: true
<<<<<<< Updated upstream
    provider: stripe
    subscriber_type: team
=======
    provider: '%env(resolve:PAYMENT_PROVIDER)%'
>>>>>>> Stashed changes
    stripe:
      private_api_key: '%env(resolve:STRIPE_PRIVATE_API_KEY)%'
      public_api_key: '%env(resolve:STRIPE_PUBLIC_API_KEY)%'
      success_url: "%env(resolve:APPLICATION_URL)%/api/payments/success/{CHECKOUT_SESSION_ID}"
      cancel_url: "%env(resolve:APPLICATION_URL)%/app/plan/select"
      return_url: "%env(resolve:APPLICATION_URL)%/app/home"
    price:
      Basic:
        monthly:
          price: '20'
          price_id: '%env(resolve:BASIC_MONTHLY_PRICE_ID)%'
          trial_day_length: 15
        yearly:
          price: '150'
          price_id: '%env(resolve:BASIC_YEARLY_PRICE_ID)%'
      Standard:
        monthly:
          price: '500'
          price_id: '%env(resolve:STANDARD_MONTHLY_PRICE_ID)%'
        yearly:
          price: '5000'
          price_id: '%env(resolve:STANDARD_YEARLY_PRICE_ID)%'
    subscriptions:
      plan:
        Free:
          is_free: true
          user_count: 1
          features:
            - send_pdf
          limit:
            team_invite:
              limit: 1
              description: "Number of users"
        Basic:
          user_count: 1
          features:
            - send_pdf
          limit:
            team_invite:
              limit: 1
              description: "Number of users"
        Standard:
          user_count: 5
          limit:
            team_invite:
              limit: 5
              description: "Number of users"