app_backoffice:
    resource: .
    type: athena

controllers:
    resource: ../../src/Controller/
    type: attribute

qa_controllers:
    resource: ../../src/Qa/Controller/
    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute

parthenon_user_controllers:
    prefix: /api
    resource: ../../src/Parthenon/User/Controller/
    type: attribute

parthenon_billing_controllers:
    prefix: /api
    resource: ../../src/Parthenon/Billing/Controller/
    type: attribute

parthenon_payments_controllers:
    prefix: /api
    resource: ../../src/Parthenon/Payments/Controller/
    type: attribute

parthenon_multi_tenancy_controllers:
    resource: ../../src/Parthenon/MultiTenancy/Controller/
    type: attribute

parthenon_ab_testing_controllers:
    resource: ../../src/Parthenon/AbTesting/Controller/
    type: attribute
