name: 🚀 Feature Request
description: RFC and ideas for new features and improvements
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of the problem the feature solves
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of how the feature should solve the problem
  - type: textarea
    id: example
    attributes:
      label: Example
      description: |
        A simple example of the new feature in action (include PHP code, YAML config, etc.)
        If the new feature changes an existing feature, include a simple before/after comparison.