services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Parthenon\Notification\EmailSenderInterface: '@Parthenon\Notification\Sender\NullEmailSender'
    Parthenon\MultiTenancy\TenantProvider\TenantProviderInterface: '@App\Qa\MultiTenant\Test\TestCurrentTenantProvider'

    Obol\Provider\ProviderInterface: '@App\Dummy\Provider\Provider'